services:

  # ------------------------------------------------------------ #
  # ------- Identity and Access Management (IAM) Service ------- #
  # ------------------------------------------------------------ #
  keycloakweb:
    image: quay.io/keycloak/keycloak:26.5
    container_name: keycloakweb
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password

      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    depends_on:
      - keycloakdb
    ports:
      - 4001:8080
      - 4002:9000

  keycloakdb:
    image: postgres:16.3
    container_name: keycloakdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  # ------------------------------------------------------------ #
  # --------------------- pgAdmin Service ---------------------- #
  # ------------------------------------------------------------ #
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - keycloakdb

  # ------------------------------------------------------------ #
  # ---------------------- Micro Service ----------------------- #
  # ------------------------------------------------------------ #
  micro.service:
    container_name: micro.service
    build:
      context: ../../spacetimewave.services/spacetimewave.micro.service/src
      dockerfile: Dockerfile
    ports:
      - "8443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://dashboard:18889
      - OTEL_RESOURCE_ATTRIBUTES=service.name=API.Service
      - AuthenticationSettings__AuthenticationType=JwtBearer
      - AuthenticationSettings__Realm=spacetimewave
      - AuthenticationSettings__MetadataUrl=http://keycloakweb:8080/realms/spacetimewave/.well-known/openid-configuration
      - AuthenticationSettings__AuthorizationUrl=http://keycloakweb:8080/realms/spacetimewave/protocol/openid-connect/auth
      - AuthenticationSettings__TokenUrl=http://keycloakweb:8080/realms/spacetimewave/protocol/openid-connect/token
      - AuthenticationSettings__Issuer=http://keycloakweb:8080/realms/spacetimewave
      - AuthenticationSettings__ClientId=micro.spacetimewave.com
      - AuthenticationSettings__Audience=account
      - AuthenticationSettings__Scopes=profile email
      - ApplicationSettings__ServerUrl=https://localhost:8443
      - ApplicationSettings__McpServerUrl=https://localhost:9443
      - ApplicationSettings__DatabaseSecretArn=arn:aws:secretsmanager:region:<account-id>:secret:<secret-name>
    networks:
      - otel
    depends_on:
      - keycloakweb
      - keycloakdb

  # ------------------------------------------------------------ #
  # ---------------- Open Telemetry Dashboard ------------------ #
  # ------------------------------------------------------------ #
  dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:13
    container_name: dashboard
    ports:
    - "18888:18888"
    environment:
    - ASPNETCORE_UI_CULTURE=en-US
    - ASPNETCORE_CULTURE=en-US
    networks:
    - otel

  # ------------------------------------------------------------ #
  # --------------------- Frontend Service --------------------- #
  # ------------------------------------------------------------ #
  frontend:
    container_name: front
    build:
      context: ../../spacetimewave.services/spacetimewave.front.service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - micro.service
    networks:
      - otel

networks:
  otel:

volumes:
  postgres_data:

